#############################zhuheng20200509
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuheng?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: zhuheng
    driver-calss-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.example.entity

#show sql
loggin:
  level:
    com:
      example:
        mapper: debug
